name: build
on:
  push:
  pull_request:
jobs:
  cross-compile-supported:
    strategy:
      fail-fast: false
      matrix:
        goos:
          - android
          - darwin
          - freebsd
          - ios
          - linux
          - windows
        goarch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: build-${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build
