name: test
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-13
          - macos-12
          - macos-11
          - windows-2022
          - windows-2019
        go:
          - "1.22"
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"
          - "1.16"
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          go test --race ./...

  testFreeBSD:
    runs-on: macos-10.15
    name: test (freebsd, 1.17)
    steps:
      - uses: actions/checkout@v4
      - name: test (freebsd, 1.17)
        id: test
        uses: vmactions/freebsd-vm@v0.1.6
        with:
          usesh: true
          prepare: pkg install -y go
          run: |
            go test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: checkout
        uses: actions/checkout@v4

      - name: gofmt
        run: |
          test -z "$(gofmt -s -d . | tee /dev/stderr)"

      - name: vet
        run: |
          go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        continue-on-error: true
        with:
          version: latest
